# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/Student/CENG3430RapidPrototype/project_1/project_1.runs/synth_1/vga_driver.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param checkpoint.writeSynthRtdsInDcp 1
set_param chipscope.maxJobs 6
set_param synth.incrementalSynthesisCache C:/Users/Student/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-18000-102-035/incrSyn
set_param xicom.use_bs_reader 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Student/CENG3430RapidPrototype/project_1/project_1.cache/wt [current_project]
set_property parent.project_path C:/Users/Student/CENG3430RapidPrototype/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part_repo_paths {C:/Users/Student/AppData/Roaming/Xilinx/Vivado/2023.2/xhub/board_store/xilinx_board_store} [current_project]
set_property board_part avnet.com:zedboard:part0:1.4 [current_project]
set_property ip_output_repo c:/Users/Student/CENG3430RapidPrototype/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_vhdl -library xil_defaultlib {
  C:/Users/Student/CENG3430RapidPrototype/project_1/project_1.srcs/sources_1/new/utilities.vhd
  C:/Users/Student/CENG3430RapidPrototype/project_1/project_1.srcs/sources_1/new/finish_scene/boom_pkg.vhd
  C:/Users/Student/CENG3430RapidPrototype/project_1/project_1.srcs/sources_1/new/click_scene/click_pkg.vhd
  C:/Users/Student/CENG3430RapidPrototype/project_1/project_1.srcs/sources_1/new/clock_divider.vhd
  C:/Users/Student/CENG3430RapidPrototype/project_1/project_1.srcs/sources_1/new/indicators_pkg/correct_pkg.vhd
  C:/Users/Student/CENG3430RapidPrototype/project_1/project_1.srcs/sources_1/new/finish_scene/defused_pkg.vhd
  C:/Users/Student/CENG3430RapidPrototype/project_1/project_1.srcs/sources_1/new/keypad_scene/keypad_at_pkg.vhd
  C:/Users/Student/CENG3430RapidPrototype/project_1/project_1.srcs/sources_1/new/keypad_scene/keypad_balloon_pkg.vhd
  C:/Users/Student/CENG3430RapidPrototype/project_1/project_1.srcs/sources_1/new/keypad_scene/keypad_hookn_pkg.vhd
  C:/Users/Student/CENG3430RapidPrototype/project_1/project_1.srcs/sources_1/new/keypad_scene/keypad_leftc_pkg.vhd
  C:/Users/Student/CENG3430RapidPrototype/project_1/project_1.srcs/sources_1/new/keypad_scene/keypad_pkg.vhd
  C:/Users/Student/CENG3430RapidPrototype/project_1/project_1.srcs/sources_1/new/keypad_scene/keypad_squidknife_pkg.vhd
  C:/Users/Student/CENG3430RapidPrototype/project_1/project_1.srcs/sources_1/new/keypad_scene/keypad_squigglyn_pkg.vhd
  C:/Users/Student/CENG3430RapidPrototype/project_1/project_1.srcs/sources_1/new/keypad_scene/keypad_upsidedowny_pkg.vhd
  C:/Users/Student/CENG3430RapidPrototype/project_1/project_1.srcs/sources_1/new/knob_bottom_pkg/knob_bottom_1_pkg.vhd
  C:/Users/Student/CENG3430RapidPrototype/project_1/project_1.srcs/sources_1/new/knob_bottom_pkg/knob_bottom_2_pkg.vhd
  C:/Users/Student/CENG3430RapidPrototype/project_1/project_1.srcs/sources_1/new/knob_bottom_pkg/knob_bottom_3_pkg.vhd
  C:/Users/Student/CENG3430RapidPrototype/project_1/project_1.srcs/sources_1/new/knob_bottom_pkg/knob_bottom_4_pkg.vhd
  C:/Users/Student/CENG3430RapidPrototype/project_1/project_1.srcs/sources_1/new/knob_down_arrow_pkg.vhd
  C:/Users/Student/CENG3430RapidPrototype/project_1/project_1.srcs/sources_1/new/knob_bottom_pkg/knob_frozen_pkg.vhd
  C:/Users/Student/CENG3430RapidPrototype/project_1/project_1.srcs/sources_1/new/knob_left_arrow_pkg.vhd
  C:/Users/Student/CENG3430RapidPrototype/project_1/project_1.srcs/sources_1/new/knob_right_arrow_pkg.vhd
  C:/Users/Student/CENG3430RapidPrototype/project_1/project_1.srcs/sources_1/new/knob_top_dial_bg_pkg.vhd
  C:/Users/Student/CENG3430RapidPrototype/project_1/project_1.srcs/sources_1/new/knob_up_arrow_pkg.vhd
  C:/Users/Student/CENG3430RapidPrototype/project_1/project_1.srcs/sources_1/new/joystick/pmod_joystick.vhd
  C:/Users/Student/CENG3430RapidPrototype/project_1/project_1.srcs/sources_1/new/joystick/spi_master.vhd
  C:/Users/Student/CENG3430RapidPrototype/project_1/project_1.srcs/sources_1/new/ssd_ctrl.vhd
  C:/Users/Student/CENG3430RapidPrototype/project_1/project_1.srcs/sources_1/new/indicators_pkg/wrong_pkg.vhd
  C:/Users/Student/CENG3430RapidPrototype/project_1/project_1.srcs/sources_1/new/wires_scene/wires_bg_pkg.vhd
  C:/Users/Student/CENG3430RapidPrototype/project_1/project_1.srcs/sources_1/new/wires_scene/wires_blue_pkg.vhd
  C:/Users/Student/CENG3430RapidPrototype/project_1/project_1.srcs/sources_1/new/wires_scene/wires_green_pkg.vhd
  C:/Users/Student/CENG3430RapidPrototype/project_1/project_1.srcs/sources_1/new/wires_scene/wires_red_pkg.vhd
  C:/Users/Student/CENG3430RapidPrototype/project_1/project_1.srcs/sources_1/new/wires_scene/wires_yellow_pkg.vhd
  C:/Users/Student/CENG3430RapidPrototype/project_1/project_1.srcs/sources_1/new/vga_driver.vhd
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Student/CENG3430RapidPrototype/project_1/project_1.srcs/constraint/lab05.xdc
set_property used_in_implementation false [get_files C:/Users/Student/CENG3430RapidPrototype/project_1/project_1.srcs/constraint/lab05.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/Users/Student/CENG3430RapidPrototype/project_1/project_1.srcs/utils_1/imports/synth_1/vga_driver.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top vga_driver -part xc7z020clg484-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef vga_driver.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file vga_driver_utilization_synth.rpt -pb vga_driver_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
